server:
  port: 8080

spring:
  application:
    name: trading-system
  datasource:
    url: jdbc:h2:mem:trading_db
    username: khoi
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


external-source:
  binance:
    baseUrl: "api.binance.com"
    path: "/api/v3/ticker/bookTicker"
    apiKey:
  huobi:
    baseUrl: "api.huobi.pro"
    path: "/market/tickers"
    apiKey:



